### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by mw0t** [supmanyu/InstaScraper#7]
I have this bug:

```
Traceback (most recent call last):
  File "C:\Users\khale\Downloads\Compressed\InstaScraper-master\InstaScraper-master\build\lib\release\Scraper.py", line 8, in <module>
    import pytest
ImportError: No module named pytest

```
and when i remove this import i get this:

```
Traceback (most recent call last):
  File "C:\Users\khale\Downloads\Compressed\InstaScraper-master\InstaScraper-master\build\lib\release\Scraper.py", line 54, in <module>
    brows = Browser()
NameError: name 'Browser' is not defined
```

**Comment by axelabbas** [comment]
add the import again (don't delete it)
And install pytest
Use this command: _**pip2 install pytest**_
